---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# paleotools

<!-- badges: start -->
<!-- badges: end -->

The goal of paleotools is to ...

## Installation

You can install the development version of the package from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mchevalier2/paleotools")
```

## Example

This is a basic example which shows you how to use the Earth Movers' Distance
(EMD) and the associated significance test.

```{r example}
library(paleotools)

EMD(1:5/sum(1:5), 6:10/sum(6:10))
EMD(1:5, 6:10) # The vectors are normalised by the function
m <- matrix(1:25, ncol=5)
for(i in 1:5) m[i,i] <- 0
EMD(1:5, 6:10, weight.m=m)
```

```{r EMD.test,  fig.show="hold"}
m1 <- matrix(abs(rnorm(500)), ncol=5) ; m1 <- m1 / apply(m1, 1, sum)
m2 <- matrix(abs(rnorm(500)), ncol=5) ; m2 <- m2 / apply(m2, 1, sum)
EMD.test(m1, m2, plot=FALSE)
res <- EMD.test(m1, m2, plot=TRUE, verbose=TRUE)
res <- EMD.test(m1, 1+m1, plot=TRUE, verbose=TRUE, nrep=100)
str(res)
```
